### ISSUE TITLE
Stopping the ticker at a specific integer

### ISSUE THREAD

**Issue by shefik** [harvesthq/tick#15]
Once the ticker starts, how can be it stopped when it reaches a specific integer?

**Comment by mtvs** [comment]
By calling the `stop()` on the `Tick` instance.

If you check the source code you can see when you initialize the plugin on a jQuery selection you get an array of `Tick` instances, one for each element in the selection.

Also if you assign a `function` to the `incremental` option, you get the reference to the `Tick` instance in `this`.

And there is a `start()` as well, that both deserve being mentioned in the docs. @harvesthq

**Comment by jkintscher** [comment]
@mtvs Good call. I’ve added coverage of the `start`/`stop` instance methods to the README in #19.
