### ISSUE TITLE
Want to flip the tick upto specific number only

### ISSUE THREAD

**Issue by rakeshadak137** [harvesthq/tick#20]
I want this tick to flip only upto certain number(e.g. 211).
It should run from 0 to 211 and then it should stop.
Currently it starts counting from 211 and goes increasing

**Comment by jkintscher** [comment]
Please see https://github.com/harvesthq/tick/issues/15.

**Comment by rakeshadak137** [comment]
Thank you.It works.

Thanks And Regards
Rakesh Adak
