### ISSUE TITLE
Events don't seem to be used anywhere

### ISSUE THREAD

**Issue by cockroachbill** [harvesthq/tick#9]
I'm trying to make use of the events to start and stop the ticker after certain things happen, but they don't seem to actually be triggered anywhere in the code. Is there something I'm just completely missing about how it's set up?

**Comment by jkintscher** [comment]
No, you’re right. This was also brought to my attention by a different user just now which reminded me of your comment. I’ve updated the README to exclude the section about events as we never got around to implement them.

If, by any chance, you ended up adding event functionality to Tick, feel free to share it through a pull request!
